name: Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: latest
          cache: 'yarn'

      - name: Lint src and check docs
        run: |
          yarn install --frozen-lockfile
          yarn pre-commit

      - name: Cypress Test
        run: |
          yarn build
          yarn test
